### PR TITLE
2 plays a month

### PR DESCRIPTION
**Pull request by debjit**
Updated with latest data provided by @atapas in this [issue](https://github.com/reactplay/activities/issues/109)

ReactPlay-presents-HACK-R-PLAY

### CODE REVIEW

**Comment by Amyx000** [comment]
Did you make changes directly in about.js in the component itself? because about.js is also used in hackeplay home.js

**Comment by debjit** [comment]
> Did you make changes directly in about.js in the component itself? because about.js is also used in hackeplay home.js

components/Hack-R-Play/About.js

> Did you make changes directly in about.js in the component itself? because about.js is also used in hackeplay home.js

Both are working. Please pull locally and try.

**Comment by debjit** [comment]
@atapas can you view this?

**Comment by atapas** [comment]
> @atapas can you view this?

Yes, added you as assignee

**Comment by atapas** [comment]
@debjit you can add reviewers now.

**Review by atapas — CHANGES_REQUESTED** [review]
Hi @debjit

image

We shouldn't recreate these components for every activity. Rather, we should reuse them across activities. So suggesting you to do this:

- Create a folder called `common` inside the `components` folder and move all common components between hack-r-play and 2playsamonth to the `common` folder. Then reuse them to both hack-r-play and 2playsamonth. You have to refactor the imports of the hack-r-play home page a bit for that, but that's ok.

- After you have done these, test both hack-r-play and 2playsamonth home pages respectively that it works as expected.

**Pull request closed without merging**
