### PR TITLE
 Handle multi line title and description

### PR DESCRIPTION
**Pull request by shrilakshmishastry**
### What defect fix done through this PR?

1. truncate title and description if multiple line 
2. change font family 
3. Change avatar look

### After the fix title and description 
image

### CODE REVIEW

**Review by atapas — COMMENTED** [review]
@shrilakshmishastry will it adjust based on resolution? I mean for a larger resolution the ellipses won’t come? Also, how will it behave with mobile?

**Comment by ammaaraslam** [comment]
@shrilakshmishastry, looks good. 
Can you adjust the spacing between each row of cards? And also add the correct font as well.

**Comment by shrilakshmishastry** [comment]
for small screen Yes it works. As per UI given title should be 2 line and the description should be 4 line . 
One more question I have no where specified height and width , does this property effected by resolution?

image

**Comment by ammaaraslam** [comment]
> for small screen Yes it works. As per UI given title should be 2 line and the description should be 4 line . One more question I have no where specified height and width , does this property effected by resolution?
> 
> image

It's affected by the size of the parent container.

**Comment by shrilakshmishastry** [comment]
so it doesn't cause any problem and always renders 2 line and 4 line right

**Comment by shrilakshmishastry** [comment]
> @shrilakshmishastry, looks good. Can you adjust the spacing between each row of cards? And also add the correct font as well.

fixed font family

**Review by ammaaraslam — COMMENTED** [review]
LGM 
@atapas

**Comment by shrilakshmishastry** [comment]
> @shrilakshmishastry also, make the status appear in one line. image

what's the resolution

**Comment by ammaaraslam** [comment]
> > @shrilakshmishastry also, make the status appear in one line. image
> 
> it's the responsive nature of grid , if I try to give width and height it gets disturb

Did you try `width: fit-content` ?

**Comment by shrilakshmishastry** [comment]
> @shrilakshmishastry decrease the spacing between the avatars. Apart from that, everything else is fine.

If I decrease gap,left  image will not look nice  so keeping it as it is

**Comment by atapas** [comment]
> 

How about like this?

image

**Comment by shrilakshmishastry** [comment]
> > 
> 
> How about like this?
> 
> image

not possible, because img is taken from  next/Image and it's rendering inside span . Whatever style I apply will be taken to img but will not be applied to span. If anyone knows solution please let me know

**Comment by ammaaraslam** [comment]
> > > 
> > 
> > 
> > How about like this?
> > image
> 
> not possible, because img is taken from next/Image and it's rendering inside span . Whatever style I apply will be taken to img but will not be applied to span. If anyone knows solution please let me know

@shrilakshmishastry, you can try adding a parent `div` to the `Image` component and try styling that parent `div`. Let me know if it works

**Comment by shrilakshmishastry** [comment]
> > > > 
> > > 
> > > 
> > > How about like this?
> > > image
> > 
> > 
> > not possible, because img is taken from next/Image and it's rendering inside span . Whatever style I apply will be taken to img but will not be applied to span. If anyone knows solution please let me know
> 
> @shrilakshmishastry, you can try adding a parent `div` to the `Image` component and try styling that parent `div`. Let me know if it works

yes it did, thanks

**Review by atapas — APPROVED** [review]

**Pull request merged**
