### PR TITLE
Winners Section

### PR DESCRIPTION
**Pull request by ammaaraslam**

### CODE REVIEW

**Comment by koustov** [comment]
This is really good just one comment. I feel the position markers (1st,2nd and 3rd) are little dim in contrast with dark background

**Comment by koustov** [comment]
One more, shouldn't this winner section be the top section? Or atleast main banner should give some focus to the Hack-R-Play results  .

**Comment by ammaaraslam** [comment]
> One more, shouldn't this winner section be the top section? Or atleast main banner should give some focus to the Hack-R-Play results .

@koustov 
how about we add a "Winners" button to the hero

**Review by koustov — APPROVED** [review]
lgtm

**Pull request merged**
