### PR TITLE
Issue 86 Status filter for idea page

### LINKED ISSUE #86: Add two more filters to submissions
**Is your feature request related to a problem? Please describe.**
Currently its hard to figure out completed and inprogress items in the idea list page. This is very much required to understand the status of the event.

**Describe the solution you'd like**
Implement a status filter for idea list page

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by koustov**
Closes #86

### CODE REVIEW

**Comment by atapas** [comment]
IMO, we should have the My Ideas filter still.

**Review by ammaaraslam — COMMENTED** [review]
I agree with @atapas that we should still have a my ideas filter. And also I think that it'd be nice to add some padding towards the left side of filters and right of the Date/Name filters.
Apart from that everything else looks good!

**Comment by koustov** [comment]
> IMO, we should have the My Ideas filter still.

You need to login in order to see "My Ideas" that's by design from the beginning

**Comment by koustov** [comment]
> I agree with @atapas that we should still have a my ideas filter. And also I think that it'd be nice to add some padding towards the left side of filters and right of the Date/Name filters. Apart from that everything else looks good!

@ammaaraslam , regarding padding, it was planned and adjusted by @nirmalkc , Do you want to re-evaluate?

**Comment by ammaaraslam** [comment]
> > IMO, we should have the My Ideas filter still.
> 
> You need to login in order to see "My Ideas" that's by design from the beginning

Yup my bad wasn't logged in... sorry :p

**Comment by ammaaraslam** [comment]
> > I agree with @atapas that we should still have a my ideas filter. And also I think that it'd be nice to add some padding towards the left side of filters and right of the Date/Name filters. Apart from that everything else looks good!
> 
> @ammaaraslam , regarding padding, it was planned and adjusted by @nirmalkc , Do you want to re-evaluate?

Oh.. if it's from design then ya sure no problem 👍🏻

**Comment by koustov** [comment]
@ammaaraslam @atapas is this ready to go?

**Comment by ammaaraslam** [comment]
> @ammaaraslam @atapas is this ready to go?

Yup, All good 👍🏻

**Review by ammaaraslam — APPROVED** [review]
Yup! All good 👍🏻

**Review by atapas — APPROVED** [review]

**Pull request merged**
