### PR TITLE
Completed Landing Page Implementation

### PR DESCRIPTION
**Pull request by ammaaraslam**
I have created the landing page from the design we decided.

The landing page includes the following sections:
- Hero
- About
- Judges & Mentors
- Partners/Sponsors
- Call To Action
- FAQs

I have added reusability to certain sections of the landing page. Once the final content is ready, I will add reusability to the rest as well.
@atapas, coding part is done, go through the code for any bugs or suggestions. And share the content once everything's fine.

### CODE REVIEW

**Comment by atapas** [comment]
@ammaaraslam 

Section wise all looks good except this one!

image

Is it like, when we have the partner name, it will appear just below the "OUR PARTNERS" heading? What will be the background color?

Will the "BE A PART OF..." section follow that?

CC: @nirmalkc

**Comment by ammaaraslam** [comment]
@atapas, done with the new project structure, let me know your review.

**Review by atapas — APPROVED** [review]

**Comment by nirmalkc** [comment]
> > @ammaaraslam
> > Section wise all looks good except this one!
> > image
> > Is it like, when we have the partner name, it will appear just below the "OUR PARTNERS" heading? What will be the background color?
> > Will the "BE A PART OF..." section follow that?
> > CC: @nirmalkc
> 
> @atapas
> 
> The heading "Our Partners" falls under a different section, to which @nirmalkc has not yet included the design for. And the section "BE A PART OF" is a different section that follows the partners section.

Partner section will have N-HOST. We will call this section as OUR SPONSOR and have N-HOST logo in it.

I will share the updated XD file.

**Comment by nirmalkc** [comment]
@ammaaraslam here are some of my observations, which you may need to fix it in the site.

- 3 boxes in the about section needs better alignment and padding as per the mockup. 
- FAQs has slight mismatch when compared with the mockup. Please fix that.
- Responsive design for each section.

Please let me know if you need a mockup for the responsive design.

**Comment by ammaaraslam** [comment]
> @ammaaraslam here are some of my observations, which you may need to fix it in the site.
> 
> * 3 boxes in the about section needs better alignment and padding as per the mockup.
> * FAQs has slight mismatch when compared with the mockup. Please fix that.
> * Responsive design for each section.
> 
> Please let me know if you need a mockup for the responsive design.

@nirmalkc, working on the fixes and the responsiveness. Please check on this [PR](https://github.com/reactplay/activities/pull/28) for more updates on that.

**Pull request merged**
