### PR TITLE
Configure TailwindCSS

### PR DESCRIPTION
**Pull request by ammaaraslam**
Added TailwindCSS to project.
- Necessary depenedencies.
- Tailwind Config.
- Dark mode Tailwind config for future use case.

### CODE REVIEW

**Comment by atapas** [comment]
@ammaaraslam How have you tested the configuration works? Can you modify the home page style a bit to demonstrate it works?

**Comment by ammaaraslam** [comment]
> @ammaaraslam How have you tested the configuration works? Can you modify the home page style a bit to demonstrate it works?

Hi @atapas, I have added a basic style to the `<a>` tag using TailwindCSS and it works.

**Comment by atapas** [comment]
> > @ammaaraslam How have you tested the configuration works? Can you modify the home page style a bit to demonstrate it works?
> 
> Hi @atapas, I have added a basic style to the `<a>` tag using TailwindCSS and it works.

Can you please resolve the conflict to merge it.

**Comment by ammaaraslam** [comment]
> > > @ammaaraslam How have you tested the configuration works? Can you modify the home page style a bit to demonstrate it works?
> > 
> > 
> > Hi @atapas, I have added a basic style to the `<a>` tag using TailwindCSS and it works.
> 
> Can you please resolve the conflict to merge it.

Done @atapas

**Review by atapas — APPROVED** [review]

**Pull request merged**
