### PR TITLE
Idea listing page implimentation 

### PR DESCRIPTION
**Pull request by shrilakshmishastry**
**Functionality added:**

1. Listing all ideas for a hackathon 
2. Fetches data from DB
3. UI Implementation for above

**Libraries added addition to present**

1. @apollo/client
2. react-virtualized

**Limitations** 

1. Currently query is written for supporting only nhost hackathon. It should be generalized to adopt for all.

**Screenshot of implementation:**

image

### CODE REVIEW

**Comment by atapas** [comment]
> https://deploy-preview-25--activities-reactplay.netlify.app

How do I test it? What's the URL?

**Comment by shrilakshmishastry** [comment]
<base-url>/ideas  as the page name is ideas

**Comment by nirmalkc** [comment]
@shrilakshmishastry here is the design for the ideas page. I can provide all the artifacts as separate PNG files.

image

**Review by koustov — APPROVED** [review]
lgtm

**Pull request merged**
